---
- name: "check if the credentials {{ namespace }}/{{ name }} exist."
  tags:
  - always
  run_once: true
  register: spec
  k8s_facts:
    kind: Secret
    namespace: "{{ namespace }}"
    name: "{{ name }}"

- when: not spec.resources and secret is defined
  tags:
  - always
  set_fact:
    credential: "{{ parameters | combine(secret|mandatory) }}"

- when: spec.resources or not secret is defined
  tags:
  - always
  set_fact:
    credential: "{{ parameters|mandatory }}"

- name: "created credentials {{ namespace }}/{{ name }}"
  tags:
  - always
  run_once: true
  k8s:
    state: present
    merge_type:
    - strategic-merge
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        labels: "{{ labels|default({}) }}"
        annotations: "{{ annotations|default({}) }}"
        namespace: "{{ namespace }}"
        name: "{{ name }}"
      type: Opaque
      stringData: "{{ credential }}"
