---
- set_fact:
    awx_configured: false

- when: awx_url is not defined
  set_fact:
    awx_url: "{{ lookup('env', 'TOWER_HOST') }}"

- when: awx_username is not defined
  set_fact:
    awx_username: "{{ lookup('env', 'TOWER_USERNAME') }}"

- when: awx_password is not defined
  set_fact:
    awx_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"

- when: awx_verify_ssl is not defined
  set_fact:
    awx_verify_ssl: "{{ lookup('env', 'TOWER_VERIFY_SSL') == '1' }}"

- when: awx_url and awx_username and awx_password
  set_fact:
    awx_configured: true

- name: lookup Kubernetes API endpoint
  register: query
  k8s_facts:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: Endpoints
    namespace: default
    name: kubernetes

- name: set Kubernetes API endpoint parameters as Ansible facts
  set_fact:
    k8s_api_host: "{{ query.resources[0]['subsets'][0]['addresses'][0]['ip'] }}"
    k8s_api_port: "{{ query.resources[0]['subsets'][0]['ports'][0]['port'] }}"

- name: lookup namespaces
  register: result
  k8s_facts:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: Namespace

- set_fact:
    k8s_namespaces: "{{ result.resources }}"

- when: http_proxy_enabled is not defined
  set_fact:
    http_proxy_enabled: true

- when: http_proxy_whitelist is not defined
  set_fact:
    http_proxy_whitelist: []

- when: http_proxy_replicas is not defined
  set_fact:
    http_proxy_replicas: 3

- when: http_proxy_cpu is not defined
  set_fact:
    http_proxy_cpu: 250m

- when: http_proxy_memory is not defined
  set_fact:
    http_proxy_memory: 256Mi

- when: logstash_enabled is not defined
  set_fact:
    logstash_enabled: true

- when: logstash_replicas is not defined
  set_fact:
    logstash_replicas: 1

- when: logstash_cpu is not defined
  set_fact:
    logstash_cpu: 500m

- when: logstash_memory is not defined
  set_fact:
    logstash_memory: 1Gi


- when: cluster_dmz_namespaces is not defined
  set_fact:
    cluster_dmz_namespaces: []

- when: cluster_ingress_controllers is not defined
  set_fact:
    cluster_ingress_controllers: []

- when: cluster_ingress_loadbalancers is not defined
  set_fact:
    cluster_ingress_loadbalancers: []
