---

- name: lookup namespaces
  register: result
  k8s_facts:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: Namespace
    label_selectors:
    - "ops.unimatrixone.io/env = {{ target_environment }}"

- set_fact:
    namespaces: "{{ result.resources }}"
    x509_trusted_issuers: false

- name: find certificates
  register: result
  find:
    paths: ../pki
    patterns: "*.crt,*.pem"

- set_fact:
    certificates: "{{ result.files }}"
    x509_trusted_issuers: "{{ result.files|bool }}"

- name: create ConfigMap holding the certificates
  with_items: "{{ namespaces }}"
  loop_control:
    loop_var: ns
  k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    force: true
    definition: "{{ lookup('template', '../templates/resources/configmap.ca-certificates.yml.j2') }}"

- name: create ConfigMap holding a bundle of the certificates
  with_items: "{{ namespaces }}"
  loop_control:
    loop_var: ns
  k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    force: true
    definition: "{{ lookup('template', '../templates/resources/configmap.ca-bundle.yml.j2') }}"
