---
- hosts: localhost
  run_once: true
  gather_facts: false
  environment:
    ANSIBLE_ROLES_PATH: "../roles"
    PYTHONPATH: ""
  vars:
    K8S_NAMESPACE_PREFIX: "ns{{ deployment_env_alias }}"
    K8S_DEPLOYMENT_ENV: "{{ deployment_env_name|mandatory }}"
    target_environment: "{{ K8S_DEPLOYMENT_ENV|default('cluster') }}"
  pre_tasks:
  - include_tasks: includes/auth.yml
  - include_tasks: includes/facts.yml
  tasks:
  - include_vars: "defaults/{{ deployment_env_name }}.yml"
  - include_vars: "vars/{{ deployment_env_name }}.yml"
  - include_tasks: tasks/k8s/main.yml
  - include_tasks: user.yml
